### PR TITLE
Bump version to v1.2.0

### PR DESCRIPTION
**Pull request by jfrerich**
### Summary
Bump version to v1.2.0

Proposal to bump Minor Version to prep for release with the following Release Notes:

#### Enhancements 
* 1402746 MM-18590 - Custom Admin Settings (#18)
* 07d7986 Add more manifest metadata (#19)

#### Fixes
* 923cec2 updated dependencies (#20)
* 8cc663d Bump Mattermost to 5.18 (#17)

### Ticket Link
https://mattermost.atlassian.net/browse/MM-22266

### CODE REVIEW

**Comment by marianunez** [comment]
@jfrerich this release requires Mattermost v5.20 that is not yet released. Just wanted to double check that we are OK we having this out first.

**Comment by hanzei** [comment]
We can even put in the Marketplace right now. The code logic makes sure it it not shown for servers < v5.20.

**Comment by jfrerich** [comment]
Sounds like we are ready to merge after remaining review.  Thanks for added info, @hanzei

**Comment by levb** [comment]
> Sounds like we are ready to merge after remaining review. Thanks for added info, @hanzei

Just be careful not to push to community, until after community.mattermost.com is on 5.20 (2/17/2020)

**Comment by DHaussermann** [comment]
Version bump was successful and End to End testing is now done. 

@aaronrothschild please advise if we have time to fix 
https://github.com/mattermost/mattermost-plugin-custom-attributes/issues/22 before we ship this release.

**Comment by aaronrothschild** [comment]
@jfrerich Can you fix the oddly formatted "delete" icon before we merge?  I think we need to add 45 degrees tilt... not much risk involved I'm assuming. ;)

**Comment by DHaussermann** [comment]
This is waiting on https://github.com/mattermost/mattermost-plugin-custom-attributes/pull/23 so we can include it in the release.

**Comment by jfrerich** [comment]
@DHaussermann, https://github.com/mattermost/mattermost-plugin-custom-attributes/pull/23 has been merged!  Can you do a quick review of this ticket?

**Comment by DHaussermann** [comment]
@jfrerich this won't have the fix for https://github.com/mattermost/mattermost-plugin-custom-attributes/pull/23
Not a huge problem. I can approve the version bump anyway but, should we sync from master first.

**Comment by jfrerich** [comment]
@dylan, master has been merged.

**Comment by DHaussermann** [comment]
- End 2 End testing completed
- Version bump was successful 
- No issues found

This is a great improvement! However, the new admin UI does not seem to be documented in the read-me. @marianunez or @aaronrothschild  please advise on next steps.

**Comment by marianunez** [comment]
@DHaussermann agreed that the new configuration screen should be documented in the Readme. I suggest that we open a ticket for it but I unfortunately do not have bandwith to complete it at this time. 

1/5 it should be included before releasing 1.2.0

**Comment by jfrerich** [comment]
@marianunez, I'll add to the README and added this ticket. https://github.com/mattermost/mattermost-plugin-custom-attributes/issues/30

As a side note, @levb and I discussed READMEs and attaching them to the actual bumped release.

* README.md changes aren’t necessarily vital.
* Documentation isn't viewable through the app and users will be looking at the latest master commit in the github repo.  So, although the README is necessary, it can be done post merge in some cases.  I'l

**Comment by marianunez** [comment]
Sound good @jfrerich! Thanks!

**Comment by jfrerich** [comment]
@DHaussermann I created a ticket for the README. Merging this now.

**Pull request merged**
